name: publish

on: ['push', 'pull_request']

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:20.9.0

    services:
      db:
        image: postgres:13
        env:
          POSTGRES_USER: prisma
          POSTGRES_PASSWORD: prisma
          POSTGRES_DB: tests
        ports:
          - '5432:5432'
      s3.docker.test:
        image: zenko/cloudserver
        env:
          REMOVE_MANAGEMENT_DISABLE: 1
          S3BACKEND: mem
        ports:
          - '8000:8000'

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Initialize Bucket
        run: pnpm run s3devdata

      - name: Setup .env
        run: |
          cp .env.test .env
          echo "BETA=false" >> .env

      - name: Build
        run: pnpm run build
      - name: Deploy database
        run: pnpm run db:deploy
      - name: Install Playwright Dependencies
        run: npx playwright install-deps
      - name: Install Playwright
        run: npx playwright install
      - name: Run Tests
        run: pnpm run test
